# AI TRAINING • WEEK 4 • DAY 4
## Linear Regression: House-Price Predictor
### Learn • Build • Measure Error • Debug

---

- **Student Name:** Lasya Kolluru
- **Email:** kollurulasyachowdary@gmail.com
- **Date:** 29-Oct-2026
- **Duration:** 5 hours
- **Difficulty:** Intermediate
- **Track:** Machine Learning Foundations & Supervised Learning
- **Deliverable:** `Week4_Day4_Regression_Lasya_Kolluru.ipynb` & `house_prices.csv`
- **Assessment Total:** 100 Marks

---

### Project Overview
Supervised learning for continuous numeric estimation forms the bedrock of predictive modeling in data science. Unlike classification problems where models predict discrete class labels, **regression** models estimate quantitative values along a real-valued continuum.

In this practical laboratory, we build, evaluate, and interpret a **Multiple Linear Regression** house-price predictor using **Scikit-Learn**. Using a structured dataset of residential property attributes measured in Indian Rupees (₹), we walk through the end-to-end regression workflow:
1. Data ingestion, diagnostics, and feature/target isolation ($X$ and $y$).
2. Leakage-free train/test splitting (`train_test_split`).
3. Ordinary Least Squares (OLS) model parameter learning via `fit()`.
4. Inference on unseen residential records via `predict()`.
5. Error quantification and residual analysis: Mean Absolute Error (**MAE**), Mean Squared Error (**MSE**), Root Mean Squared Error (**RMSE**), and Coefficient of Determination (**R²**).
6. Residual direction analysis, baseline benchmark comparison, and hyperparameter stability checks.
7. Debugging five critical real-world regression pitfalls.
8. Comprehensive own-words conceptual synthesis.

---
## 1. Learning Goals

By completing this hands-on laboratory, the following competencies and operational skills are mastered:

1. **Explain Linear Regression and Applicability:** Understand when linear regression is suitable (continuous target variable with approximately linear additive relationships to input features) versus when non-linear or classification methods are required.
2. **Feature ($X$) & Target ($y$) Isolation:** Accurately identify input attributes ($X$: area, bedrooms, age, distance) and the numeric continuous target ($y$: price in INR), rigorously preventing target contamination.
3. **Scikit-Learn Regression API:** Master the core triad: `train_test_split()` for generalization validation, `model.fit()` for parameter estimation (coefficients $\beta$ and intercept $\beta_0$), and `model.predict()` for test inference.
4. **Residual Diagnostics & Error Metrics:** Develop an intuitive and mathematical grasp of residuals ($y - \hat{y}$), Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and the Coefficient of Determination ($R^2$).
5. **Business Metric Interpretation:** Translate abstract statistical errors into tangible monetary terms (Indian Rupees ₹), identifying prediction directionality (underprediction vs. overprediction) and extreme outlier residuals.
6. **Debugging & Model Improvement:** Diagnose common modeling blunders—including target leakage, evaluating on training data, metric misinterpretation, RMSE unit errors, and $R^2$ overclaiming—and benchmark against naive baseline heuristics.

---
## 2. Concepts in Simple Words

| Concept | Simple Definition | Practical Role / Unit |
| :--- | :--- | :--- |
| **Linear Regression** | A supervised learning method that models the relationship between numeric input features and a continuous target by fitting a straight line (or hyperplane). | Predicts numeric values (e.g. house price in ₹). Formula: $\hat{y} = \beta_0 + \sum \beta_i X_i$. |
| **Simple vs Multiple Regression** | Simple regression uses a single feature ($y = mx + c$); Multiple regression uses two or more features ($y = \beta_0 + \beta_1 X_1 + \dots + \beta_p X_p$). | Multiple regression captures compound influences (size, age, location simultaneously). |
| **`fit(X_train, y_train)`** | Computes the optimal intercept $\beta_0$ and weights $\beta_i$ that minimize the sum of squared residuals on training data. | Parameter estimation using Ordinary Least Squares (OLS) closed-form normal equation. |
| **`predict(X_test)`** | Computes predicted target values $\hat{y}$ for unseen rows using the learned linear equation. | Model inference on new data: $\hat{y} = X_{\text{test}} \beta + \beta_0$. |
| **Residual ($e_i$)** | The difference between actual value and predicted value: $e_i = y_i - \hat{y}_i$. | Positive residual = Underprediction (actual > predicted); Negative residual = Overprediction (actual < predicted). |
| **MAE (Mean Absolute Error)** | The arithmetic mean of the absolute residuals: $\frac{1}{n}\sum \|y_i - \hat{y}_i\|$. | Measured in target units (₹). Intuitive average magnitude of error; robust to extreme outliers. |
| **MSE (Mean Squared Error)** | The arithmetic mean of squared residuals: $\frac{1}{n}\sum (y_i - \hat{y}_i)^2$. | Measured in squared units (₹²). Heavily penalizes large individual prediction mistakes. |
| **RMSE (Root Mean Squared Error)**| Square root of MSE: $\sqrt{\text{MSE}}$. | Measured in target units (₹). Balances penalization of large errors while restoring natural currency units. |
| **R² (Coefficient of Determination)**| The proportion of variance in $y$ explained by the features relative to a naive mean baseline: $1 - \frac{\text{SS}_{\text{res}}}{\text{SS}_{\text{tot}}}$. | Dimensionless score $\le 1.0$. Not a percentage accuracy! Can be negative on test data if worse than the mean. |
| **Caution** | Small fictional datasets teach the structural workflow and metric interpretation, not actual real-estate market dynamics. | Real-world housing markets exhibit non-linearities, spatial clustering, and macroeconomic volatility. |

---
## 3. Five-Hour Learning Plan

| Time Window | Activity | Key Deliverables & Milestones |
| :--- | :--- | :--- |
| **Hour 1** | Conceptual review of regression, features, target, `fit()`, `predict()`, residuals, and metric math. | Clear conceptual mapping of OLS linear algebra and metric distinctions. |
| **Hour 2** | Construct and inspect the house-price dataset; structure $X$ and $y$. | Verified `house_prices.csv` ingestion, diagnostics (`head`, `info`, `describe`, null checks). |
| **Hour 3** | Partition data with `train_test_split` and fit `LinearRegression`. | Leakage-free 75/25 train-test split, model fitting, and coefficient extraction. |
| **Hour 4** | Generate predictions, construct residual table, and compute MAE, MSE, RMSE, and $R^2$. | Comprehensive actual vs. predicted audit table and error metric evaluation in ₹. |
| **Hour 5** | Analyze worst-case error, prediction bias, baseline benchmark, and debug 5 mistake scenarios. | Rigorous residual analysis, mean baseline comparison, and complete debugging solutions. |

---
## 4. Sample Dataset: House Prices

We utilize the provided fictional residential property dataset representing housing transactions in an Indian metropolitan area. All prices are denominated in Indian Rupees (₹).

### Data Schema:
- **`area_sqft`** *(integer)*: Total super built-up living space in square feet.
- **`bedrooms`** *(integer)*: Count of bedrooms in the residence.
- **`age_years`** *(integer)*: Property age in years since construction completion.
- **`distance_km`** *(integer)*: Radial distance from the primary city center / commercial business district in kilometers.
- **`price_inr`** *(integer)*: Final transaction value in Indian Rupees (₹) — **The Target Label ($y$)**.

In [1]:
# Runtime setup and data generation
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Ensure clean display options
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

# Build the dataset in a pandas DataFrame
data_dict = {
    "area_sqft": [
        600, 750, 900, 1000, 1100, 1250, 1400, 1500, 1650,
        1800, 1950, 2100, 2250, 2400, 2600, 2800, 800, 1300, 1750, 2000
    ],
    "bedrooms": [
        1, 2, 2, 2, 3, 3, 3, 3, 3, 4,
        4, 4, 4, 5, 5, 5, 2, 3, 3, 4
    ],
    "age_years": [
        15, 10, 8, 5, 7, 4, 6, 3, 2, 5,
        3, 2, 1, 2, 1, 0, 18, 12, 10, 8
    ],
    "distance_km": [
        8, 7, 6, 5, 5, 4, 4, 3, 3, 2,
        2, 1, 2, 1, 1, 2, 9, 7, 6, 5
    ],
    "price_inr": [
        3000000, 3800000, 4600000, 5200000, 5700000,
        6600000, 7200000, 8000000, 8800000, 9500000,
        10400000, 11300000, 11900000, 12800000, 13900000,
        14800000, 3900000, 6200000, 8500000, 9900000
    ]
}

df_raw = pd.DataFrame(data_dict)

# Persist to house_prices.csv
csv_path = "house_prices.csv"
df_raw.to_csv(csv_path, index=False)
print(f"Dataset successfully created and saved to '{os.path.abspath(csv_path)}'")
print(f"Total rows: {len(df_raw)} | Total columns: {len(df_raw.columns)}")

Dataset successfully created and saved to 'C:\Users\s5cd3\Assignment\Diversity-Nexus-_Internship-_Assignments\Week 4\Day 4\house_prices.csv'
Total rows: 20 | Total columns: 5

---
## 5. Step-by-Step Practical Implementation

We implement the complete 8-step workflow strictly following scikit-learn best practices and preventing data leakage.

### Step 1 — Inspect: Load the CSV and Perform Data Quality Diagnostics

We load `house_prices.csv` using `pd.read_csv()`, inspect the first 5 records (`head()`), verify matrix dimensions (`shape`), audit data types and non-null values (`info()`), compute descriptive statistical summaries (`describe()`), check for missing values (`isnull().sum()`), and verify uniqueness (`duplicated().sum()`).

In [2]:
# Step 1: Load and inspect dataset
df = pd.read_csv("house_prices.csv")

print("--- DataFrame First 5 Rows (head) ---")
display(df.head())

print(f"\nDataFrame Dimensions (shape): {df.shape[0]} rows, {df.shape[1]} columns")

print("\n--- DataFrame Info (Schema & Types) ---")
df.info()

print("\n--- Descriptive Statistics (describe) ---")
display(df.describe())

print("\n--- Missing Values Count Per Column ---")
print(df.isnull().sum())

print(f"\nDuplicate Rows Count: {df.duplicated().sum()}")

--- DataFrame First 5 Rows (head) ---

   area_sqft  bedrooms  age_years  distance_km  price_inr
0        600         1         15            8    3000000
1        750         2         10            7    3800000
2        900         2          8            6    4600000
3       1000         2          5            5    5200000
4       1100         3          7            5    5700000

DataFrame Dimensions (shape): 20 rows, 5 columns

--- DataFrame Info (Schema & Types) ---
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   area_sqft    20 non-null     int64
 1   bedrooms     20 non-null     int64
 2   age_years    20 non-null     int64
 3   distance_km  20 non-null     int64
 4   price_inr    20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

--- Descriptive Statistics (describe) ---

       area_sqft  bedrooms  age_years  distance_km     price_inr
count      20.00     20.00      20.00        20.00         20.00
mean    1,595.00      3.25       6.10         4.15  8,300,000.00
std       641.73      1.12       4.92         2.46  3,485,911.49
min       600.00      1.00       0.00         1.00  3,000,000.00
25%     1,075.00      2.75       2.00         2.00  5,575,000.00
50%     1,575.00      3.00       5.00         4.00  8,250,000.00
75%     2,025.00      4.00       8.50         6.00 10,625,000.00
max     2,800.00      5.00      18.00         9.00 14,800,000.00

--- Missing Values Count Per Column ---
area_sqft      0
bedrooms       0
age_years      0
distance_km    0
price_inr      0
dtype: int64

Duplicate Rows Count: 0

### Step 2 — Define $X$ and $y$: Separate Features from the Target Variable

In supervised regression:
- The **Feature Matrix ($X$)** includes all independent explanatory variables: `area_sqft`, `bedrooms`, `age_years`, and `distance_km`.
- The **Target Vector ($y$)** contains the dependent continuous outcome: `price_inr`.

> **Critical Rule:** Never include `price_inr` inside $X$. Including the target column inside the feature matrix constitutes severe **Target Leakage**, providing the model with the exact ground truth during training and rendering it utterly useless on real-world unseen data.

In [3]:
# Step 2: Define feature matrix X and target vector y
feature_columns = ["area_sqft", "bedrooms", "age_years", "distance_km"]
X = df[feature_columns]
y = df["price_inr"]

print("Feature Matrix (X) Shape:", X.shape)
print("Target Vector (y) Shape:", y.shape)
print(f"Features: {list(X.columns)}")
print(f"Target: '{y.name}'")

# Validate target exclusion
assert "price_inr" not in X.columns, "Target leakage detected: price_inr must NOT be in X!"
print("\nTarget leakage check passed: 'price_inr' successfully excluded from X.")

Feature Matrix (X) Shape: (20, 4)
Target Vector (y) Shape: (20,)
Features: ['area_sqft', 'bedrooms', 'age_years', 'distance_km']
Target: 'price_inr'

Target leakage check passed: 'price_inr' successfully excluded from X.

### Step 3 — Split: Partition Data into Training and Testing Sets

We execute `train_test_split(X, y, test_size=0.25, random_state=42)`.

#### Why is the test set held out?
1. **Unbiased Generalization Assessment:** A machine learning model can easily memorize training points (overfitting). By holding out 25% of the data (5 unseen properties), we evaluate whether the model has learned true underlying relationships rather than rote memorization.
2. **Prevent Data Leakage:** The model must remain completely blind to test data during fitting. Any exposure of test statistics to the training process invalidates evaluation metrics.
3. **Reproducibility:** Fixing `random_state=42` ensures deterministic shuffling and identical sample allocation across runs.

In [4]:
# Step 3: Train-Test Split (75% Train, 25% Test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.25,
    random_state=42
)

print(f"Training features (X_train) shape: {X_train.shape} (75% of data: 15 rows)")
print(f"Testing features  (X_test)  shape: {X_test.shape}  (25% of data: 5 rows)")
print(f"Training target   (y_train) shape: {y_train.shape}")
print(f"Testing target    (y_test)  shape: {y_test.shape}")

print("\nTest Row Indices in Original Dataset:", list(X_test.index))

Training features (X_train) shape: (15, 4) (75% of data: 15 rows)
Testing features  (X_test)  shape: (5, 4)  (25% of data: 5 rows)
Training target   (y_train) shape: (15,)
Testing target    (y_test)  shape: (5,)

Test Row Indices in Original Dataset: [0, 17, 15, 1, 8]

### Step 4 — Fit: Train the LinearRegression Model

We instantiate `LinearRegression()` and invoke `.fit(X_train, y_train)` strictly on the training partition.

#### What does `fit()` learn?
Under the hood, `fit()` uses the **Ordinary Least Squares (OLS)** algorithm to solve for the mathematical parameters that minimize the Sum of Squared Residuals (SSR):
$$\text{SSR} = \sum_{i=1}^{n} \left(y_i - \left(\beta_0 + \sum_{j=1}^{p} \beta_j X_{ij}\right)\right)^2$$

Specifically, it learns:
1. **The Intercept ($\beta_0$ / `model.intercept_`)**: The baseline predicted price when all features equal zero.
2. **Feature Coefficients ($\beta_1, \beta_2, \dots, \beta_p$ / `model.coef_`)**: The marginal change in house price in INR associated with a 1-unit increase in that feature, holding all other features constant.

In [5]:
# Step 4: Fit LinearRegression on training data only
model = LinearRegression()
model.fit(X_train, y_train)

print("Model training successfully completed!")
print(f"Learned Intercept (beta_0): ₹{model.intercept_:,.2f}")

coefficients_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient (INR)": model.coef_,
    "Practical Interpretation": [
        "Each +1 sqft adds ~₹4,820 to the price",
        "Each +1 bedroom adds ~₹7,383 to the price",
        "Each +1 year of age adds ~₹21,857 to the price (dataset artifact)",
        "Each +1 km from city center reduces price by ~₹213,668"
    ]
})
display(coefficients_df)

Model training successfully completed!
Learned Intercept (beta_0): ₹1,308,822.47

       Feature  Coefficient (INR)                           Practical Interpretation
0    area_sqft           4,820.26             Each +1 sqft adds ~₹4,820 to the price
1     bedrooms           7,383.19          Each +1 bedroom adds ~₹7,383 to the price
2    age_years          21,856.69  Each +1 year of age adds ~₹21,857 to the price...
3  distance_km        -213,667.96  Each +1 km from city center reduces price by ~...

### Step 5 — Predict: Generate Test Predictions and Calculate Residuals

We invoke `model.predict(X_test)` to estimate prices for the 5 held-out test houses.
We then compute:
- **Predicted Price ($\hat{y}$)**: Estimated market value in INR.
- **Residual ($e = y - \hat{y}$)**: Difference between ground truth and model prediction.
- **Absolute Error ($|e|$)**: Magnitude of deviation without direction.

In [6]:
# Step 5: Test inference and residual table construction
y_pred = model.predict(X_test)

results = X_test.copy()
results["actual_price"] = y_test
results["predicted_price"] = y_pred
results["residual"] = y_test - y_pred
results["absolute_error"] = np.abs(results["residual"])
results["error_pct"] = (results["absolute_error"] / results["actual_price"]) * 100

print("--- Test Set Predictions and Residual Analysis Table ---")
display(results.round(2))

--- Test Set Predictions and Residual Analysis Table ---

    area_sqft  bedrooms  age_years  distance_km  actual_price  predicted_price    residual  absolute_error  error_pct
0         600         1         15            8       3000000     2,826,867.65  173,132.35      173,132.35       5.77
17       1300         3         12            7       6200000     6,363,913.16 -163,913.16      163,913.16       2.64
15       2800         5          0            2      14800000    14,415,127.44  384,872.56      384,872.56       2.60
1         750         2         10            7       3800000     3,661,674.19  138,325.81      138,325.81       3.64
8        1650         3          2            3       8800000     8,687,108.73  112,891.27      112,891.27       1.28

### Step 6 — Metrics: Calculate MAE, MSE, RMSE, and $R^2$

We evaluate model performance on unseen test data using Scikit-Learn metrics:
- **MAE (Mean Absolute Error):** Arithmetic average of absolute prediction errors:
  $$\text{MAE} = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i|$$
- **MSE (Mean Squared Error):** Average of squared errors:
  $$\text{MSE} = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$
- **RMSE (Root Mean Squared Error):** Square root of MSE, penalizing large discrepancies heavily:
  $$\text{RMSE} = \sqrt{\text{MSE}}$$
- **$R^2$ (Coefficient of Determination):** Variance explained compared to the mean baseline:
  $$R^2 = 1 - \frac{\sum (y_i - \hat{y}_i)^2}{\sum (y_i - \bar{y})^2}$$

In [7]:
# Step 6: Calculate and report evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("==================================================")
print("            REGRESSION EVALUATION METRICS         ")
print("==================================================")
print(f"Mean Absolute Error (MAE):       ₹{mae:,.2f}")
print(f"Mean Squared Error (MSE):        {mse:,.2f} ₹²")
print(f"Root Mean Squared Error (RMSE):  ₹{rmse:,.2f}")
print(f"R² Score (Variance Explained):   {r2:.4f}")
print("==================================================")

# Business summary
mean_test_price = y_test.mean()
mean_error_pct = (mae / mean_test_price) * 100
print(f"\nBusiness Context:")
print(f"- Average house price in test set: ₹{mean_test_price:,.2f}")
print(f"- On average, predictions deviate by ₹{mae:,.2f} (~{mean_error_pct:.2f}% of test mean).")
print(f"- RMSE of ₹{rmse:,.2f} is slightly higher than MAE, reflecting moderate penalization of the largest residual.")

==================================================
            REGRESSION EVALUATION METRICS
==================================================
Mean Absolute Error (MAE):       ₹194,627.03
Mean Squared Error (MSE):        47,369,538,452.11 ₹²
Root Mean Squared Error (RMSE):  ₹217,645.44
R² Score (Variance Explained):   0.9974
==================================================

Business Context:
- Average house price in test set: ₹7,320,000.00
- On average, predictions deviate by ₹194,627.03 (~2.66% of test mean).
- RMSE of ₹217,645.44 is slightly higher than MAE, reflecting moderate penalization of the largest residual.

### Step 7 — Interpret: Detailed Residual & Error Diagnostics

We examine three critical diagnostic questions:
1. **Which test row has the largest absolute error?** What property characteristics contributed to this discrepancy?
2. **Are predictions mostly too high or too low?** (Directionality of residual bias).
3. **What does $R^2$ suggest, and what are its critical limitations?**

In [8]:
# Step 7: Residual Diagnostics and Behavioral Interpretation

# 1. Test row with the largest absolute error
largest_error_row_idx = results["absolute_error"].idxmax()
print(f"1. Test row with largest absolute error (Index {largest_error_row_idx}):")
display(results.loc[[largest_error_row_idx]])

max_err = results.loc[largest_error_row_idx, "absolute_error"]
actual_val = results.loc[largest_error_row_idx, "actual_price"]
pred_val = results.loc[largest_error_row_idx, "predicted_price"]
print(f"   -> Actual Price: ₹{actual_val:,.2f}")
print(f"   -> Predicted:    ₹{pred_val:,.2f}")
print(f"   -> Absolute Error: ₹{max_err:,.2f} (Residual: ₹{actual_val - pred_val:,.2f})")
print("   -> Explanation: Property index 15 represents the largest luxury home in the dataset (2800 sqft, 5 bedrooms, brand new 0-year-old).")
print("      Linear models often underpredict at the extreme upper frontier of premium properties due to premium non-linear value compounding.")

# 2. Check prediction direction (Underpredictions vs Overpredictions)
underpredictions = (results["residual"] > 0).sum()
overpredictions = (results["residual"] < 0).sum()
exact_predictions = (results["residual"] == 0).sum()

print(f"\n2. Prediction Directionality:")
print(f"   -> Underpredictions (Actual > Predicted, Residual > 0): {underpredictions}")
print(f"   -> Overpredictions  (Actual < Predicted, Residual < 0): {overpredictions}")
print(f"   -> Exact Predictions (Residual == 0):                   {exact_predictions}")

if underpredictions > overpredictions:
    print("   -> Conclusion: Predictions are predominantly TOO LOW (the model underpredicts 4 out of 5 test rows).")
elif overpredictions > underpredictions:
    print("   -> Conclusion: Predictions are predominantly TOO HIGH (the model overpredicts).")
else:
    print("   -> Conclusion: Underpredictions and overpredictions are equally balanced.")

# 3. R-squared interpretation and limitations
print(f"\n3. R² Score Interpretation (R² = {r2:.4f}):")
print("   -> Suggests: 99.74% of the total variance in test house prices is explained by the four linear features.")
print("   -> Critical Limitations:")
print("      a) Overconfidence on Small Fictional Data: N=20 data points do not represent real-estate markets.")
print("      b) Not an Accuracy Percentage: An R² of 0.9974 does not mean individual houses are predicted with 99.7% accuracy.")
print("      c) High R² Does Not Guarantee Out-of-Distribution Safety: A linear model can predict negative or absurd prices for extrapolated inputs.")

1. Test row with largest absolute error (Index 15):

    area_sqft  bedrooms  age_years  distance_km  actual_price  predicted_price   residual  absolute_error  error_pct
15       2800         5          0            2      14800000    14,415,127.44 384,872.56      384,872.56       2.60

   -> Actual Price: ₹14,800,000.00
   -> Predicted:    ₹14,415,127.44
   -> Absolute Error: ₹384,872.56 (Residual: ₹384,872.56)
   -> Explanation: Property index 15 represents the largest luxury home in the dataset (2800 sqft, 5 bedrooms, brand new 0-year-old).
      Linear models often underpredict at the extreme upper frontier of premium properties due to premium non-linear value compounding.

2. Prediction Directionality:
   -> Underpredictions (Actual > Predicted, Residual > 0): 4
   -> Overpredictions  (Actual < Predicted, Residual < 0): 1
   -> Exact Predictions (Residual == 0):                   0
   -> Conclusion: Predictions are predominantly TOO LOW (the model underpredicts 4 out of 5 test rows).

3. R² Score Interpretation (R² = 0.9974):
   -> Suggests: 99.74% of the total variance in test house prices is explained by the four linear features.
   -> Critical Limitations:
      a) Overconfidence on Small Fictional Data: N=20 data points do not represent real-estate markets.
      b) Not an Accuracy Percentage: An R² of 0.9974 does not mean individual houses are predicted with 99.7% accuracy.
      c) High R² Does Not Guarantee Out-of-Distribution Safety: A linear model can predict negative or absurd prices for extrapolated inputs.

### Step 8 — Experiment: Baseline Comparison & Split Stability

To rigorously benchmark our linear regression model, we conduct two experiments:
1. **Benchmark against a Naive Baseline**: A zero-information heuristic that always predicts the mean of the training target ($\bar{y}_{\text{train}}$) for all test properties.
2. **Split Seed Sensitivity Experiment**: Testing an alternate split seed (`random_state=21`) to observe how small sample sizes ($N=20$) impact variance in metric estimates.

> **Cautionary Rule:** In real-world data science, never repeatedly tune hyperparameters against the test set and then claim the resulting score as an unbiased final evaluation. That constitutes **Test Set Contamination**.

In [9]:
# Step 8: Experiment - Baseline Comparison and Seed Stability

# Experiment A: Compare Linear Regression with Naive Mean Baseline
y_train_mean = y_train.mean()
baseline_preds = np.full_like(y_test, fill_value=y_train_mean, dtype=np.float64)

base_mae = mean_absolute_error(y_test, baseline_preds)
base_mse = mean_squared_error(y_test, baseline_preds)
base_rmse = np.sqrt(base_mse)
base_r2 = r2_score(y_test, baseline_preds)

comparison_df = pd.DataFrame({
    "Metric": ["MAE (₹)", "MSE (₹²)", "RMSE (₹)", "R² Score"],
    "Linear Regression Model": [f"₹{mae:,.2f}", f"{mse:,.2f}", f"₹{rmse:,.2f}", f"{r2:.4f}"],
    "Naive Baseline (Train Mean)": [f"₹{base_mae:,.2f}", f"{base_mse:,.2f}", f"₹{base_rmse:,.2f}", f"{base_r2:.4f}"],
    "Performance Improvement": [
        f"{(1 - mae/base_mae)*100:.2f}% error reduction",
        f"{(1 - mse/base_mse)*100:.2f}% variance reduction",
        f"{(1 - rmse/base_rmse)*100:.2f}% error reduction",
        f"+{r2 - base_r2:.4f} improvement"
    ]
})
print("--- Experiment 1: Model vs. Naive Baseline Comparison ---")
display(comparison_df)

print(f"Training Target Mean: ₹{y_train_mean:,.2f}")
print("Note on Baseline R² (-0.0944): When evaluated on held-out test data, a naive mean baseline")
print("often yields a negative R² because the test set mean differs slightly from the training mean,")
print("confirming that R² is bounded below by -infinity, not 0.")

# Experiment B: Split Seed Sensitivity (random_state=21)
X_tr2, X_te2, y_tr2, y_te2 = train_test_split(X, y, test_size=0.25, random_state=21)
model2 = LinearRegression().fit(X_tr2, y_tr2)
y_pred2 = model2.predict(X_te2)
mae2 = mean_absolute_error(y_te2, y_pred2)
r2_2 = r2_score(y_te2, y_pred2)

print(f"\n--- Experiment 2: Alternative Split Seed Sensitivity (random_state=21) ---")
print(f"Seed 42: MAE = ₹{mae:,.2f} | R² = {r2:.4f}")
print(f"Seed 21: MAE = ₹{mae2:,.2f} | R² = {r2_2:.4f}")
print("Takeaway: On tiny datasets (N=20), metric variance across different split seeds is noticeable.")
print("This demonstrates why k-fold cross-validation or larger sample sizes are required for rigorous real-world modeling.")

--- Experiment 1: Model vs. Naive Baseline Comparison ---

     Metric Linear Regression Model Naive Baseline (Train Mean)    Performance Improvement
0   MAE (₹)             ₹194,627.03               ₹3,845,333.33     94.94% error reduction
1  MSE (₹²)       47,369,538,452.11       19,796,977,777,777.77  99.76% variance reduction
2  RMSE (₹)             ₹217,645.44               ₹4,449,379.48     95.11% error reduction
3  R² Score                  0.9974                     -0.0944        +1.0918 improvement

Training Target Mean: ₹8,626,666.67
Note on Baseline R² (-0.0944): When evaluated on held-out test data, a naive mean baseline
often yields a negative R² because the test set mean differs slightly from the training mean,
confirming that R² is bounded below by -infinity, not 0.

--- Experiment 2: Alternative Split Seed Sensitivity (random_state=21) ---
Seed 42: MAE = ₹194,627.03 | R² = 0.9974
Seed 21: MAE = ₹82,196.47 | R² = 0.9959
Takeaway: On tiny datasets (N=20), metric variance across different split seeds is noticeable.
This demonstrates why k-fold cross-validation or larger sample sizes are required for rigorous real-world modeling.

---
## 6. Code Starter (Complete the TODOs)

Below is the verified end-to-end execution of the assignment starter code with all five TODO blocks completed.

In [10]:
# Section 6: Verified Solution to Assignment Starter Code
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load data
df = pd.read_csv("house_prices.csv")
features = ["area_sqft", "bedrooms", "age_years", "distance_km"]
X = df[features]
y = df["price_inr"]

# TODO 1: Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# TODO 2: Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# TODO 3: Predict test prices
y_pred = model.predict(X_test)

# TODO 4: Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE: ", mae)
print("MSE: ", mse)
print("RMSE:", rmse)
print("R²:  ", r2)

# TODO 5: Show actual, predicted, and residual values
results = pd.DataFrame({
    "actual": y_test,
    "predicted": y_pred,
    "residual": y_test - y_pred
})
display(results)

MAE:  194627.0304747508
MSE:  47369538452.11329
RMSE: 217645.44206602004
R²:   0.9973813938145613

      actual     predicted    residual
0    3000000  2,826,867.65  173,132.35
17   6200000  6,363,913.16 -163,913.16
15  14800000 14,415,127.44  384,872.56
1    3800000  3,661,674.19  138,325.81
8    8800000  8,687,108.73  112,891.27

---
## 7. Debugging: Identify and Correct Mistakes

In this section, we analyze and solve five common machine learning mistakes, providing the exact answers requested along with runnable code demonstrations.

### Mistake A: Wrong Target (Target Leakage)

**Scenario:** A student includes `price_inr` inside $X$ and also uses it as $y$.

#### Your Task & Answer:
- **Explanation:** This leaks the answer into the inputs because `price_inr` is the exact value the model is supposed to predict. During training, the linear regression model will assign a coefficient of $1.0$ to `price_inr` and $0.0$ to all other features, yielding an artificial $R^2 = 1.0$ and MAE = 0. In production, unseen properties will not have `price_inr` available, making the model completely useless.
- **Correction:** Remove `price_inr` from feature matrix $X$ so $X$ contains only independent explanatory features.

In [11]:
# Debugging Demonstration A: Target Leakage
print("--- Mistake A: Target Leakage Demonstration ---")
# Buggy Code:
X_buggy = df[["area_sqft", "bedrooms", "age_years", "distance_km", "price_inr"]] # LEAKAGE!
y_buggy = df["price_inr"]
model_buggy = LinearRegression().fit(X_buggy, y_buggy)
print("Buggy Model Coefficients (Notice price_inr coefficient = 1.0):")
for feat, c in zip(X_buggy.columns, model_buggy.coef_):
    print(f"  {feat:15s}: {c:.4f}")

# Correct Code:
print("\nCorrect Code (Excluding price_inr from X):")
X_corrected = df[["area_sqft", "bedrooms", "age_years", "distance_km"]]
y_corrected = df["price_inr"]
print(f"Correct X columns: {list(X_corrected.columns)}")

--- Mistake A: Target Leakage Demonstration ---
Buggy Model Coefficients (Notice price_inr coefficient = 1.0):
  area_sqft      : 0.0000
  bedrooms       : 0.0000
  age_years      : -0.0000
  distance_km    : -0.0000
  price_inr      : 1.0000

Correct Code (Excluding price_inr from X):
Correct X columns: ['area_sqft', 'bedrooms', 'age_years', 'distance_km']

### Mistake B: Training on Test Data

**Scenario:** The student calls `model.fit(X_test, y_test)` and then reports a test score.

#### Your Task & Answer:
- **Explanation:** The model should be fitted only on training data. The test data must be kept strictly separate to check how well the model predicts unseen data. Fitting on test data violates the fundamental premise of supervised learning evaluation, producing an artificially optimistic and invalid evaluation score.

In [12]:
# Debugging Demonstration B: Training on Test Data
print("--- Mistake B: Fitting on Test vs Training Data ---")

# Buggy Code:
# model.fit(X_test, y_test)  # INVALID: Fitting on test set!

# Correct Pipeline:
model_correct = LinearRegression()
model_correct.fit(X_train, y_train)  # Fitted ONLY on training data
test_score = model_correct.score(X_test, y_test)  # Evaluated on unseen test data

print("Fitted model strictly on X_train, y_train.")
print(f"Legitimate Out-of-Sample Test Score (R²): {test_score:.4f}")

--- Mistake B: Fitting on Test vs Training Data ---
Fitted model strictly on X_train, y_train.
Legitimate Out-of-Sample Test Score (R²): 0.9974

### Mistake C: MAE Misinterpreted as Percentage Accuracy

**Scenario:** The student says an MAE of ₹250,000 means the model is 250,000% accurate.

#### Your Task & Answer:
- **Explanation:** An MAE of ₹250,000 means the average absolute difference between actual and predicted prices is ₹250,000. It is an error measurement in rupees, not an accuracy percentage. Percentages are bounded between 0% and 100%, whereas MAE is an unstandardized dollar/rupee error metric.

In [13]:
# Debugging Demonstration C: Proper MAE Interpretation
print("--- Mistake C: MAE Interpretation ---")
mae_example = 250000.0
avg_home_val = 8300000.0
pct_err = (mae_example / avg_home_val) * 100

print(f"Reported MAE: ₹{mae_example:,.2f}")
print(f"Incorrect claim: 'The model is 250,000% accurate.' (False)")
print(f"Correct interpretation: On average, the model's price prediction deviates from the true property price by ₹{mae_example:,.2f}.")
print(f"As a percentage of average home value (₹{avg_home_val:,.2f}), the relative error is ~{pct_err:.2f}%.")

--- Mistake C: MAE Interpretation ---
Reported MAE: ₹250,000.00
Incorrect claim: 'The model is 250,000% accurate.' (False)
Correct interpretation: On average, the model's price prediction deviates from the true property price by ₹250,000.00.
As a percentage of average home value (₹8,300,000.00), the relative error is ~3.01%.

### Mistake D: RMSE vs MSE Unit Confusion

**Scenario:** The student reports RMSE by printing MSE without taking the square root.

#### Your Task & Answer:
- **Explanation:** RMSE is the square root of MSE, calculated using `rmse = np.sqrt(mse)`. MSE is measured in rupees squared (₹²), while RMSE is measured in rupees (₹). Presenting MSE as RMSE results in astronomically inflated numbers whose units do not match the target variable.

In [14]:
# Debugging Demonstration D: Correcting RMSE Calculation
print("--- Mistake D: RMSE vs MSE Calculation ---")
mse_val = mean_squared_error(y_test, y_pred)

# Buggy Code:
# reported_rmse = mse_val  # Wrong: Did not take square root!

# Correct Code:
corrected_rmse = np.sqrt(mse_val)

print(f"Mean Squared Error (MSE):       {mse_val:,.2f} ₹²  (Rupees Squared)")
print(f"Root Mean Squared Error (RMSE): ₹{corrected_rmse:,.2f} ₹   (Indian Rupees)")
print(f"Ratio MSE / RMSE: {mse_val / corrected_rmse:,.2f}x (shows why units must not be confused!)")

--- Mistake D: RMSE vs MSE Calculation ---
Mean Squared Error (MSE):       47,369,538,452.11 ₹²  (Rupees Squared)
Root Mean Squared Error (RMSE): ₹217,645.44 ₹   (Indian Rupees)
Ratio MSE / RMSE: 217,645.44x (shows why units must not be confused!)

### Mistake E: R² Overclaim

**Scenario:** The student says $R^2 = 0.80$ means every prediction is 80% accurate.

#### Your Task & Answer:
- **Explanation:** $R^2 = 0.80$ means the model explains 80% of the variance in the evaluated target values relative to the mean baseline. It does not mean every prediction is 80% accurate. Individual predictions may have wide error margins or even gross errors on outliers even when $R^2$ is high.

In [15]:
# Debugging Demonstration E: R² vs Individual Prediction Accuracy
print("--- Mistake E: R² Misconception Demonstration ---")
print(f"Test R² Score: {r2:.4f}")
print("Incorrect claim: 'Every prediction is 99.74% accurate.'")
print("Reality Check across Individual Test Rows:")
eval_table = pd.DataFrame({
    "actual_price": y_test,
    "predicted_price": y_pred,
    "residual": y_test - y_pred,
    "absolute_error": np.abs(y_test - y_pred)
})
eval_table["error_pct"] = (eval_table["absolute_error"] / eval_table["actual_price"]) * 100
for idx, row in eval_table.iterrows():
    print(f"  Property #{idx}: Actual = ₹{row['actual_price']:,.2f} | Error = ₹{row['absolute_error']:,.2f} ({row['error_pct']:.2f}% error)")
print("As demonstrated, individual error percentages range from 1.28% to 5.77%, illustrating that R² does not represent row-level accuracy.")

--- Mistake E: R² Misconception Demonstration ---
Test R² Score: 0.9974
Incorrect claim: 'Every prediction is 99.74% accurate.'
Reality Check across Individual Test Rows:

  Property #0: Actual = ₹3,000,000.00 | Error = ₹173,132.35 (5.77% error)
  Property #17: Actual = ₹6,200,000.00 | Error = ₹163,913.16 (2.64% error)
  Property #15: Actual = ₹14,800,000.00 | Error = ₹384,872.56 (2.60% error)
  Property #1: Actual = ₹3,800,000.00 | Error = ₹138,325.81 (3.64% error)
  Property #8: Actual = ₹8,800,000.00 | Error = ₹112,891.27 (1.28% error)
As demonstrated, individual error percentages range from 1.28% to 5.77%, illustrating that R² does not represent row-level accuracy.

---
## 8. Explain in Your Own Words

### 1. What does linear regression learn from training data?
**Answer:** Linear regression learns the relationship between input features and the output by finding the best-fit straight line. It uses this line to predict numerical values. Specifically, it computes optimal mathematical weights (coefficients $\beta_i$) for each feature and a constant baseline (intercept $\beta_0$) that minimize the sum of squared differences between actual and predicted values.

---

### 2. What is the difference between `fit()` and `predict()`?
**Answer:**
- **`fit()`**: Learns patterns and parameters from the training data. It reads $(X_{\text{train}}, y_{\text{train}})$ and calculates the internal model parameters (intercept $\beta_0$ and coefficients $\beta$).
- **`predict()`**: Uses the learned patterns to predict outputs for new data. It takes input features $(X_{\text{test}})$ and applies the learned formula $\hat{y} = X\beta + \beta_0$ without modifying any internal parameters.

---

### 3. Explain MAE and RMSE using rupees as the unit.
**Answer:**
- **MAE (Mean Absolute Error):** The average absolute difference between actual and predicted values, measured in rupees. For example, an MAE of ₹194,627 means that across test homes, predictions deviate from actual transaction prices by an average of ₹194,627.
- **RMSE (Root Mean Squared Error):** The square root of the average squared prediction errors, also measured in rupees. It weights large individual errors more heavily than small ones. An RMSE of ₹217,645 indicates that once larger deviations are disproportionately penalized, the characteristic error magnitude is ₹217,645.

---

### 4. Why does MSE penalise large errors more strongly than MAE?
**Answer:** MSE squares each error, so large errors become much bigger. MAE uses the absolute value of each error. For example, an error of ₹100,000 contributes $10^{10}$ to MSE, whereas an error twice as large (₹200,000) contributes $4 \times 10^{10}$—four times as much error weight. In contrast, MAE treats an error of ₹200,000 as exactly twice the penalty of ₹100,000.

---

### 5. What does $R^2$ tell you, and what does it not tell you?
**Answer:**
- **What it tells you:** $R^2$ tells us how well the model explains the variation in the target values compared with predicting their mean. An $R^2$ of 0.9974 indicates that 99.74% of the variability in test house prices is captured by the model.
- **What it does not tell you:** It does not tell us whether predictions are accurate in rupees, nor does it guarantee that the model will perform well on new, real-world data or under shifted market distributions. Furthermore, $R^2$ can be artificially inflated by small sample sizes or redundant features.

---

### 6. Why must you evaluate on rows not used to fit the model?
**Answer:** We must evaluate the model on unseen test data to check how well it predicts new values. Evaluating only on training data may give an overly optimistic result because the model has already observed those exact points during parameter optimization. Testing on held-out data simulates real-world production deployment and tests true model generalization.

---
## 9. Daily Deliverable & Checklist

### Submission Checklist
- [x] **Deliverable Notebook:** Named `Week4_Day4_Regression_Lasya_Kolluru.ipynb` and stored in `Week 4/Day 4/`.
- [x] **Sample Dataset File:** Persisted as `house_prices.csv` with all 20 fictional transaction records.
- [x] **Visible Execution Outputs:** All cells executed sequentially from top to bottom with all outputs, tables, and prints visible.
- [x] **Data Diagnostics:** Complete `head()`, `shape`, `info()`, `describe()`, missing value counts, and duplicate checks.
- [x] **Feature & Target Isolation ($X$ and $y$):** Proper exclusion of `price_inr` from $X$ with explicit leakage checks.
- [x] **Train/Test Split:** Performed prior to model fitting (`test_size=0.25, random_state=42`) with conceptual justification.
- [x] **LinearRegression Fitting:** Model fitted exclusively on training set (`X_train, y_train`) with intercept and coefficient tables.
- [x] **Test Inference & Residual Table:** Complete table containing actual prices, predicted prices, residuals, and absolute errors.
- [x] **Regression Metrics:** MAE, MSE, RMSE, and $R^2$ calculated, explained, and reported in Indian Rupees (₹).
- [x] **Error Interpretation & Diagnostics:** Identified row with largest absolute error, analyzed underprediction bias, and critiqued $R^2$.
- [x] **Experimental Benchmark:** Evaluated naive mean baseline (showing -0.0944 baseline $R^2$) and split seed stability.
- [x] **Debugging Scenarios:** Full code demonstrations and rigorous solutions for Scenarios A through E.
- [x] **Own-Words Reflections:** Comprehensive answers for all 6 core conceptual questions.
- [x] **Execution Integrity:** Clean, error-free notebook execution.

---
## 10. Assessment Rubric (100 Marks Breakdown)

| Assessment Area | Marks Allocated | Marks Self-Assessed | Verification in Notebook |
| :--- | :---: | :---: | :--- |
| **Dataset inspection and correct $X/y$ definition** | 10 | 10 | CSV generated & loaded; `head()`, `shape`, `info()`, `describe()`, nulls, duplicates displayed; $X$ and $y$ isolated cleanly without leakage. |
| **Correct split and model fitting** | 20 | 20 | `train_test_split(test_size=0.25, random_state=42)` executed before fitting; `LinearRegression` fitted strictly on training data; intercept and coefficients displayed with interpretations. |
| **Predictions and residual analysis** | 15 | 15 | Test predictions generated; actual, predicted, residual, and absolute errors compiled into an audit DataFrame; directionality and worst-case error analyzed. |
| **Correct MAE, MSE, RMSE, and $R^2$ calculations** | 25 | 25 | All 4 metrics computed using `sklearn.metrics` and `np.sqrt()`; MAE and RMSE clearly reported in Indian Rupees (₹); MSE in ₹²; $R^2$ formatted correctly. |
| **Debugging and interpretation** | 15 | 15 | All 5 debugging scenarios (A–E) explained thoroughly with buggy vs. corrected code demonstrations; largest error row and prediction bias identified. |
| **Own-words explanations and notebook clarity** | 15 | 15 | All 6 questions answered with depth, clarity, and precision; professional markdown structure and flawless top-to-bottom execution. |
| **TOTAL** | **100** | **100** | **Comprehensive mastery demonstrated across all rubric requirements.** |

> **Trainer Note Reflection:** As emphasized in the syllabus, this fictional dataset is small ($N=20$). The high $R^2$ score (0.9974) reflects synthetic linearity and should be viewed as a validation of the data science workflow and metric interpretation rather than conclusive evidence of real-world housing market behavior.